### ISSUE TITLE
Some webnovel novels failed to download

### ISSUE THREAD

**Issue by Anangaya** [mHaisham/novelsave#10]
Here is the error

[✓] Scraping novelovel[2K[1G
Traceback (most recent call last):
  File "c:\users\Anangaya\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\Anangaya\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Anangaya\AppData\Local\Programs\Python\Python38\Scripts\novelsave.exe\__main__.py", line 7, in <module>
  File "c:\users\Anangaya\appdata\local\programs\python\python38\lib\site-packages\novelsave\__main__.py", line 81, in main
    novelsave.update(force_cover=args.force_cover)
  File "c:\users\Anangaya\appdata\local\programs\python\python38\lib\site-packages\novelsave\websave.py", line 32, in update
    novel = Novel.from_url(UrlTools.to_novel_url(self.novel_id))
  File "c:\users\Anangaya\appdata\local\programs\python\python38\lib\site-packages\webnovel\models\novel.py", line 51, in from_url
    novel.rating = float(info_elems[3].find('strong').text) / 5.0,
ValueError: could not convert string to float: ''

**Comment by mHaisham** [comment]
Could you check whether the `webnovelbot` package is up to date

**Comment by Anangaya** [comment]
Thanks! updating webnovel solved the problem.
